Repository felixdivo/ros2-easy-test, pull requests merged in 2024-06, with the labels that each got.

#41 Remove the makefun dependency
  .github/workflows/python-package.yaml
  .readthedocs.yaml
  ros2_easy_test/ros2_easy_test/decorators.py
  ros2_easy_test/setup.py
Labels: maintenance

#42 Allow acceptable return codes to be passed
  ros2_easy_test/ros2_easy_test/decorators.py
Labels: enhancement

#43 Update README.md
  README.md
  ros2_easy_test/ros2_easy_test/decorators.py
Labels: documentation, maintenance

#44 Abandon deploy-to-pypi
  .github/workflows/python-release.yaml
  README.md
Labels: maintenance

#47 Add package urls
  ros2_easy_test/package.xml
Labels: maintenance

#49 Update link in README
  README.md
Labels: documentation
